services:
  - type: web
    name: otp-bomber
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

  - type: web
    name: phishing-tool
    runtime: python
    rootDir: phishing
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn phis:app
