services:
  - type: web
    name: otp-bomber
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app

  - type: web
    name: phishing-tool
    runtime: python
    buildCommand: cd phishing && pip install -r requirements.txt
    startCommand: cd phishing && gunicorn phis:app
